openapi: 3.0.0
info:
  title: Category API
  version: 1.0.8
  description: API for managing categories
paths:
  /category/create:
    post:
      summary: Create a new category
      operationId: createCategory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Smartphones"
                enabled:
                  type: boolean
                  example: true
              required:
                - name
                - enabled
      responses:
        "200":
          description: Category created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoryResponse"
        "400":
          description: Validation error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "500":
          description: Standard internal error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
  /category/update:
    put:
      summary: Update an existing category
      operationId: updateCategory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  example: "678b74a36fc2b2605c6f579d"
                name:
                  type: string
                  example: "Smartphones"
                enabled:
                  type: boolean
                  example: true
                version:
                  type: integer
                  example: 1
              required:
                - id
                - name
                - enabled
                - version
      responses:
        "200":
          description: Category updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoryResponse"
        "412":
          description: Versions mismatch
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "400":
          description: Validation error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "500":
          description: Standard internal error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
  /category/get/{id}:
    get:
      summary: Get a category by ID
      operationId: getCategoryById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Category retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoryResponse"
        "404":
          description: Category not found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "500":
          description: Standard internal error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
  /category/list:
    get:
      summary: Get a list of all categories
      operationId: getAll
      responses:
        "200":
          description: List of categories retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CategoryResponse"
        "500":
          description: Standard internal error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
components:
  schemas:
    CategoryResponse:
      type: object
      required:
        - id
        - version
        - name
        - enabled
        - createdAt
        - modifiedAt
      properties:
        id:
          type: string
          example: "678b74a36fc2b2605c6f579d"
        version:
          type: integer
          example: 1
        name:
          type: string
          example: "Smartphones"
        enabled:
          type: boolean
          example: true
        createdAt:
          type: string
          format: date-time
          example: "2023-01-01T00:00:00Z"
        modifiedAt:
          type: string
          format: date-time
          example: "2023-01-02T00:00:00Z"
    Problem:
      type: object
      description: RFC7807 Problem Details
      required: [type, title, status]
      properties:
        type: { type: string, format: uri }
        title: { type: string }
        status: { type: integer }
        detail: { type: string }
        instance: { type: string, format: uri }
        traceId: { type: string }
        errors:
          type: array
          items:
            type: object
            properties:
              field: { type: string }
              message: { type: string }
