openapi: 3.0.0
info:
  title: Category API
  version: 1.0.0
  description: API for managing categories
paths:
  /category/create:
    post:
      summary: Create a new category
      operationId: createCategory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Smartphones"
                enabled:
                  type: boolean
                  example: true
              required:
                - name
                - enabled
      responses:
        '200':
          description: Category created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryResponse'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Standard internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /category/update:
    put:
      summary: Update an existing category
      operationId: updateCategory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  example: "678b74a36fc2b2605c6f579d"
                name:
                  type: string
                  example: "Smartphones"
                enabled:
                  type: boolean
                  example: true
                version:
                  type: integer
                  example: 1
              required:
                - id
                - name
                - enabled
                - version
      responses:
        '200':
          description: Category updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryResponse'
        '412':
          description: Versions mismatch
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Standard internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /category/get/{id}:
    get:
      summary: Get a category by ID
      operationId: getCategoryById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Category retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryResponse'
        '404':
          description: Category not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Standard internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /category/list:
    get:
      summary: Get a list of all categories
      operationId: getAll
      responses:
        '200':
          description: List of categories retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoryResponse'
        '500':
          description: Standard internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    CategoryResponse:
      type: object
      required:
        - id
        - version
        - name
        - enabled
        - createdAt
        - modifiedAt
      properties:
        id:
          type: string
          example: "678b74a36fc2b2605c6f579d"
        version:
          type: integer
          example: 1
        name:
          type: string
          example: "Smartphones"
        enabled:
          type: boolean
          example: true
        createdAt:
          type: string
          format: date-time
          example: "2023-01-01T00:00:00Z"
        modifiedAt:
          type: string
          format: date-time
          example: "2023-01-02T00:00:00Z"
    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          example: 404
        message:
          type: string
          example: "Category not found"
        details:
          type: string
          example: "Optional additional information about the error"