// Code generated by generate-events.sh. DO NOT EDIT.
package events

import "reflect"

// Event type constants - match Avro schema names
const (
	EventTypeCategoryCreated = "CategoryCreatedEvent"
	EventTypeCategoryUpdated = "CategoryUpdatedEvent"
)

// Event is a sealed interface that all event types must implement.
// This enables exhaustiveness checking when using type switches.
type Event interface {
	isEvent() // unexported method seals the interface
}

func (*CategoryCreatedEvent) isEvent() {}

func (*CategoryUpdatedEvent) isEvent() {}

// Topic constants - Kafka topics from AsyncAPI spec
const (
	TopicCatalogCategoryEvents = "catalog.category.events"
)

// Schema name constants - Avro schema full names (namespace.name)
const (
	SchemaNameCategoryCreated = "com.ecommerce.events.category.CategoryCreatedEvent"
	SchemaNameCategoryUpdated = "com.ecommerce.events.category.CategoryUpdatedEvent"
)

// TypeRegistration contains schema registration data for TypeMapping.
type TypeRegistration struct {
	GoType     reflect.Type
	SchemaJSON []byte
	SchemaName string
	Topic      string
}

// TypeRegistrations contains all event type registrations.
// Use this to register all schemas in your microservice.
var TypeRegistrations = []TypeRegistration{
	{
		GoType:     reflect.TypeOf(CategoryCreatedEvent{}),
		SchemaJSON: CategoryCreatedCombinedSchema,
		SchemaName: SchemaNameCategoryCreated,
		Topic:      TopicCatalogCategoryEvents,
	},
	{
		GoType:     reflect.TypeOf(CategoryUpdatedEvent{}),
		SchemaJSON: CategoryUpdatedCombinedSchema,
		SchemaName: SchemaNameCategoryUpdated,
		Topic:      TopicCatalogCategoryEvents,
	},
}
