// Code generated by avro/gen. DO NOT EDIT.
package events

import (
	"time"
)

// Common event metadata used by all domain events. Contains technical/observability fields separate from business payload.
type EventMetadata struct {
	// Unique event identifier (UUID).
	EventID string `avro:"event_id" json:"event_id"`
	// Type of the event (e.g., CategoryCreated, CategoryUpdated).
	EventType string `avro:"event_type" json:"event_type"`
	// Source service that produced the event.
	Source string `avro:"source" json:"source"`
	// Event creation timestamp in milliseconds since epoch.
	Timestamp time.Time `avro:"timestamp" json:"timestamp"`
	// OpenTelemetry trace ID for distributed tracing.
	TraceID *string `avro:"trace_id" json:"trace_id"`
	// Correlation ID for request tracking across services.
	CorrelationID *string `avro:"correlation_id" json:"correlation_id"`
}

// Business data for category creation event.
type CategoryCreatedPayload struct {
	// Unique category identifier (UUID).
	CategoryID string `avro:"category_id" json:"category_id"`
	// Category name.
	Name string `avro:"name" json:"name"`
	// Whether the category is enabled.
	Enabled bool `avro:"enabled" json:"enabled"`
	// Entity version for optimistic locking.
	Version int `avro:"version" json:"version"`
	// Category creation timestamp.
	CreatedAt time.Time `avro:"created_at" json:"created_at"`
	// Category last modification timestamp.
	ModifiedAt time.Time `avro:"modified_at" json:"modified_at"`
}

// Event emitted when a new category is created.
type CategoryCreatedEvent struct {
	// Event metadata containing technical and observability fields.
	Metadata EventMetadata `avro:"metadata" json:"metadata"`
	// Category business data at the time of creation.
	Payload CategoryCreatedPayload `avro:"payload" json:"payload"`
}

// Business data for category update event.
type CategoryUpdatedPayload struct {
	// Unique category identifier (UUID).
	CategoryID string `avro:"category_id" json:"category_id"`
	// Category name.
	Name string `avro:"name" json:"name"`
	// Whether the category is enabled.
	Enabled bool `avro:"enabled" json:"enabled"`
	// Entity version for optimistic locking.
	Version int `avro:"version" json:"version"`
	// Category creation timestamp.
	CreatedAt time.Time `avro:"created_at" json:"created_at"`
	// Category last modification timestamp.
	ModifiedAt time.Time `avro:"modified_at" json:"modified_at"`
}

// Event emitted when a category is updated.
type CategoryUpdatedEvent struct {
	// Event metadata containing technical and observability fields.
	Metadata EventMetadata `avro:"metadata" json:"metadata"`
	// Category business data after the update.
	Payload CategoryUpdatedPayload `avro:"payload" json:"payload"`
}
