// Code generated by generate-events.sh. DO NOT EDIT.
package events

import _ "embed"

//go:embed asyncapi.yaml
var AsyncAPISpec []byte

//go:embed schemas/category_created.avsc
var CategoryCreatedSchema []byte

//go:embed schemas/category_updated.avsc
var CategoryUpdatedSchema []byte

//go:embed schemas/event_metadata.avsc
var EventMetadataSchema []byte

// Combined schemas with EventMetadata inlined for Avro serialization

//go:embed schemas/category_created_combined.json
var CategoryCreatedCombinedSchema []byte

//go:embed schemas/category_updated_combined.json
var CategoryUpdatedCombinedSchema []byte

