// Code generated by eventgen. DO NOT EDIT.
package events

import _ "embed"


//go:embed asyncapi.yaml
var AsyncAPISpec []byte


// Event schemas with EventMetadata inlined (ready for Avro serialization)

//go:embed schemas/category_created.avsc
var CategoryCreatedSchema []byte


//go:embed schemas/category_updated.avsc
var CategoryUpdatedSchema []byte


