// Code generated by avro/gen. DO NOT EDIT.
package events

import (
	"github.com/Sokol111/ecommerce-commons/pkg/messaging/kafka/events"
	"time"
)

// Business data for category creation event.
type CategoryCreatedPayload struct {
	// Unique category identifier (UUID).
	CategoryID string `avro:"category_id" json:"category_id"`
	// Category name.
	Name string `avro:"name" json:"name"`
	// Whether the category is enabled.
	Enabled bool `avro:"enabled" json:"enabled"`
	// Entity version for optimistic locking.
	Version int `avro:"version" json:"version"`
	// Category creation timestamp.
	CreatedAt time.Time `avro:"created_at" json:"created_at"`
	// Category last modification timestamp.
	ModifiedAt time.Time `avro:"modified_at" json:"modified_at"`
}

// Event envelope for CategoryCreated.
type CategoryCreatedEvent struct {
	// Event metadata containing technical and observability fields.
	Metadata events.EventMetadata `avro:"metadata" json:"metadata"`
	// Business data for category created event.
	Payload CategoryCreatedPayload `avro:"payload" json:"payload"`
}

// Business data for category update event.
type CategoryUpdatedPayload struct {
	// Unique category identifier (UUID).
	CategoryID string `avro:"category_id" json:"category_id"`
	// Category name.
	Name string `avro:"name" json:"name"`
	// Whether the category is enabled.
	Enabled bool `avro:"enabled" json:"enabled"`
	// Entity version for optimistic locking.
	Version int `avro:"version" json:"version"`
	// Category creation timestamp.
	CreatedAt time.Time `avro:"created_at" json:"created_at"`
	// Category last modification timestamp.
	ModifiedAt time.Time `avro:"modified_at" json:"modified_at"`
}

// Event envelope for CategoryUpdated.
type CategoryUpdatedEvent struct {
	// Event metadata containing technical and observability fields.
	Metadata events.EventMetadata `avro:"metadata" json:"metadata"`
	// Business data for category updated event.
	Payload CategoryUpdatedPayload `avro:"payload" json:"payload"`
}

// Event interface implementations

func (e *CategoryCreatedEvent) GetMetadata() *events.EventMetadata { return &e.Metadata }

func (e *CategoryUpdatedEvent) GetMetadata() *events.EventMetadata { return &e.Metadata }
