// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"time"
)

// CategoryResponse defines model for CategoryResponse.
type CategoryResponse struct {
	CreatedAt  time.Time `json:"createdAt"`
	Enabled    bool      `json:"enabled"`
	Id         string    `json:"id"`
	ModifiedAt time.Time `json:"modifiedAt"`
	Name       string    `json:"name"`
	Version    int       `json:"version"`
}

// Problem RFC7807 Problem Details
type Problem struct {
	Detail *string `json:"detail,omitempty"`
	Errors *[]struct {
		Field   *string `json:"field,omitempty"`
		Message *string `json:"message,omitempty"`
	} `json:"errors,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	TraceId  *string `json:"traceId,omitempty"`
	Type     string  `json:"type"`
}

// CreateCategoryJSONBody defines parameters for CreateCategory.
type CreateCategoryJSONBody struct {
	Enabled bool   `json:"enabled"`
	Name    string `json:"name"`
}

// UpdateCategoryJSONBody defines parameters for UpdateCategory.
type UpdateCategoryJSONBody struct {
	Enabled bool   `json:"enabled"`
	Id      string `json:"id"`
	Name    string `json:"name"`
	Version int    `json:"version"`
}

// CreateCategoryJSONRequestBody defines body for CreateCategory for application/json ContentType.
type CreateCategoryJSONRequestBody CreateCategoryJSONBody

// UpdateCategoryJSONRequestBody defines body for UpdateCategory for application/json ContentType.
type UpdateCategoryJSONRequestBody UpdateCategoryJSONBody
