// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a new category
	// (POST /category/create)
	CreateCategory(c *gin.Context)
	// Get a category by ID
	// (GET /category/get/{id})
	GetCategoryById(c *gin.Context, id string)
	// Get a paginated list of categories with filtering and sorting
	// (GET /category/list)
	GetList(c *gin.Context, params GetListParams)
	// Update an existing category
	// (PUT /category/update)
	UpdateCategory(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// CreateCategory operation middleware
func (siw *ServerInterfaceWrapper) CreateCategory(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateCategory(c)
}

// GetCategoryById operation middleware
func (siw *ServerInterfaceWrapper) GetCategoryById(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCategoryById(c, id)
}

// GetList operation middleware
func (siw *ServerInterfaceWrapper) GetList(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetListParams

	// ------------- Required query parameter "page" -------------

	if paramValue := c.Query("page"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument page is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "size" -------------

	if paramValue := c.Query("size"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument size is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "size", c.Request.URL.Query(), &params.Size)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter size: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "enabled" -------------

	err = runtime.BindQueryParameter("form", true, false, "enabled", c.Request.URL.Query(), &params.Enabled)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter enabled: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", c.Request.URL.Query(), &params.Order)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter order: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetList(c, params)
}

// UpdateCategory operation middleware
func (siw *ServerInterfaceWrapper) UpdateCategory(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateCategory(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/category/create", wrapper.CreateCategory)
	router.GET(options.BaseURL+"/category/get/:id", wrapper.GetCategoryById)
	router.GET(options.BaseURL+"/category/list", wrapper.GetList)
	router.PUT(options.BaseURL+"/category/update", wrapper.UpdateCategory)
}

type CreateCategoryRequestObject struct {
	Body *CreateCategoryJSONRequestBody
}

type CreateCategoryResponseObject interface {
	VisitCreateCategoryResponse(w http.ResponseWriter) error
}

type CreateCategory200JSONResponse CategoryResponse

func (response CreateCategory200JSONResponse) VisitCreateCategoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateCategory400ApplicationProblemPlusJSONResponse Problem

func (response CreateCategory400ApplicationProblemPlusJSONResponse) VisitCreateCategoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateCategory500ApplicationProblemPlusJSONResponse Problem

func (response CreateCategory500ApplicationProblemPlusJSONResponse) VisitCreateCategoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetCategoryByIdRequestObject struct {
	Id string `json:"id"`
}

type GetCategoryByIdResponseObject interface {
	VisitGetCategoryByIdResponse(w http.ResponseWriter) error
}

type GetCategoryById200JSONResponse CategoryResponse

func (response GetCategoryById200JSONResponse) VisitGetCategoryByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCategoryById404ApplicationProblemPlusJSONResponse Problem

func (response GetCategoryById404ApplicationProblemPlusJSONResponse) VisitGetCategoryByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetCategoryById500ApplicationProblemPlusJSONResponse Problem

func (response GetCategoryById500ApplicationProblemPlusJSONResponse) VisitGetCategoryByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetListRequestObject struct {
	Params GetListParams
}

type GetListResponseObject interface {
	VisitGetListResponse(w http.ResponseWriter) error
}

type GetList200JSONResponse CategoryListResponse

func (response GetList200JSONResponse) VisitGetListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetList400ApplicationProblemPlusJSONResponse Problem

func (response GetList400ApplicationProblemPlusJSONResponse) VisitGetListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetList500ApplicationProblemPlusJSONResponse Problem

func (response GetList500ApplicationProblemPlusJSONResponse) VisitGetListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateCategoryRequestObject struct {
	Body *UpdateCategoryJSONRequestBody
}

type UpdateCategoryResponseObject interface {
	VisitUpdateCategoryResponse(w http.ResponseWriter) error
}

type UpdateCategory200JSONResponse CategoryResponse

func (response UpdateCategory200JSONResponse) VisitUpdateCategoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateCategory400ApplicationProblemPlusJSONResponse Problem

func (response UpdateCategory400ApplicationProblemPlusJSONResponse) VisitUpdateCategoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateCategory412ApplicationProblemPlusJSONResponse Problem

func (response UpdateCategory412ApplicationProblemPlusJSONResponse) VisitUpdateCategoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(412)

	return json.NewEncoder(w).Encode(response)
}

type UpdateCategory500ApplicationProblemPlusJSONResponse Problem

func (response UpdateCategory500ApplicationProblemPlusJSONResponse) VisitUpdateCategoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Create a new category
	// (POST /category/create)
	CreateCategory(ctx context.Context, request CreateCategoryRequestObject) (CreateCategoryResponseObject, error)
	// Get a category by ID
	// (GET /category/get/{id})
	GetCategoryById(ctx context.Context, request GetCategoryByIdRequestObject) (GetCategoryByIdResponseObject, error)
	// Get a paginated list of categories with filtering and sorting
	// (GET /category/list)
	GetList(ctx context.Context, request GetListRequestObject) (GetListResponseObject, error)
	// Update an existing category
	// (PUT /category/update)
	UpdateCategory(ctx context.Context, request UpdateCategoryRequestObject) (UpdateCategoryResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// CreateCategory operation middleware
func (sh *strictHandler) CreateCategory(ctx *gin.Context) {
	var request CreateCategoryRequestObject

	var body CreateCategoryJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCategory(ctx, request.(CreateCategoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCategory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateCategoryResponseObject); ok {
		if err := validResponse.VisitCreateCategoryResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCategoryById operation middleware
func (sh *strictHandler) GetCategoryById(ctx *gin.Context, id string) {
	var request GetCategoryByIdRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCategoryById(ctx, request.(GetCategoryByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCategoryById")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetCategoryByIdResponseObject); ok {
		if err := validResponse.VisitGetCategoryByIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetList operation middleware
func (sh *strictHandler) GetList(ctx *gin.Context, params GetListParams) {
	var request GetListRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetList(ctx, request.(GetListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetList")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetListResponseObject); ok {
		if err := validResponse.VisitGetListResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateCategory operation middleware
func (sh *strictHandler) UpdateCategory(ctx *gin.Context) {
	var request UpdateCategoryRequestObject

	var body UpdateCategoryJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateCategory(ctx, request.(UpdateCategoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateCategory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateCategoryResponseObject); ok {
		if err := validResponse.VisitUpdateCategoryResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xXTY/bNhP+KwTf95Cizlp29iPVbbNBggWKYpFNe2iQAyWObAYiqZCjZNWF/3vB0Yct",
	"i97GLbDZAgV8sEjOzEPO8wyH9zy3urIGDHqe3nOfr0EL+nslEFbWNT8rj+/AV9Z4COOVsxU4VECrFIIe",
	"//m/g4Kn/H/zred553be+xz8bWYcmwp4yoVzognflVhRHAk+d6pCZQ1P+VXtHBhkYZaZWmfg+IzDndBV",
	"CTxdDH6UQViBC568+iPi6RcyZrZgBJlV4MjrrrtlEvOHFkU5dfg+DHeYBrcjcEnE3WbGHXyulQPJ0w+8",
	"N+qQEPQ+4sfB2mafIMeAZXKSk8zkDgSCvMTwMWDhy2T54nmyeJ4s3idJSr/f+YwX1mmBPOVSIDxHpSl8",
	"G9WjU2YVooIRWRkA73hEV8OwNLO2BGHCWjVexs8vXmYXp+LFeZEvs+V5cpafF2cXP8lYHG2lKtQD4Jd/",
	"A7wRGsbubrVwWK2tAR8z+ALOU4rvHyTafibDjnrTLur25GY7eRntM5bkG2ezEvSUcu/eXF28TC5Yt4C9",
	"BhSqJP6MOCBpPPybptI568bKHdsWCkoZNdXgfSfSvblNZBP7+lbGozA5mQ+Jq52KZcCjwNrvBNpVo8IS",
	"ovjQiRyu49jbgb+KvJdSmu0jDqimGdvQ9go7TdjlzTUrrGNaGLFSZsXyVr+qZV67lUHU7PLmeodEKV+c",
	"JCfLJOC3FRhRKZ7yFyfJSUIVA9d0RPPOZzNvKUYptZ4kFBIrApZwLPyK5vtovN0seHxlZUOlwxoEQ4ai",
	"qkqVk+n8k2/F0FbzKWOOqQ5HinEvIXuiimdiaxBA0EBbKwnsMkmO2upx11qIv3eB9bnt9M98nefgfVGX",
	"Jeni9EFAVav0H48D1heQCJ7fRKkk+WZUCgKEs8eFcIvCSOEkC6p2RpQ9kqD8WmvhmoGsTDADX3vZNLRm",
	"S/gV4PxeyU0As4II498C9gl41VxLko0TGhBCDfxwz1UAFKTUl+y0LeRjEs12Nr3P0I9PhWAO0Cn4EqXY",
	"6WPmd0BkLLLC1kY+WZK9BWRiYBfLGnb9eo9jpWpL6SF+hT55yqsxmJtt98qe6dojy4CtiOCO4VoYlvzA",
	"Zy0ZP9dAtbljY9cYHubjbouilVG61gfalW/tiNkzLe7YIjmIqetSvwFTaKi1uOtAhX74OIhvVBmOKGtY",
	"V/NZdwnHgW27rQiW+JUUiwmlZGiZtw5Z1hw6BOtwHMiEbQ2X1OF+b3v37a6Z3Hz7uG4DHOtk4JDwORgZ",
	"GgrrWFjWfh1KGFmNwEooRF1S7ww+pzu1RS/oiwZHULtl36P6jV6iEamH+cDibW/1YC3877o9XAmr0KVS",
	"m1JOD/WrwjUrSJGBecJIkkjfqG1LZl3Jvg+tI0XzV5r+rm3oP3mkPuZ7cvKK7H39q1rflg9PUouni+Wj",
	"QmjT55lWXgvM10+2HrQiZcIwuFMed96uoQnfbP4MAAD//wsb7MlCFAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
